### ISSUE TITLE
User category and resource management (multiple subissues)

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#11]
- Define user categories (base/intermediate/advanced/admin) and manage the resources (disk space and computational power) assigned to each user category / specific user (this is very important for the correct use of the Cineca cluster)

- Implement a limitation on resource usage for users who are not in the upgraded category (to be evaluated the differentiation of resource usage limitation between public and registered user, but not in the upgraded category)

**Comment by akaitoua** [comment]
I am ready for any help, Andrea is more in this now. @andreagulino, if you feel you have tooo much, let me know in an email.

**Comment by acanakoglu** [comment]
limiting the disk usage, not the cpu

**Comment by andreagulino** [comment]
@marcomass 
We decided just to limit the resources for guest users, right?
If you want also a super-user group it requires lot of changes both in GMQL and  GMQL-WEB.

Can you re-define this issue?

**Comment by akaitoua** [comment]
@andreagulino, The user authentication is handled by the Web interface service. Thus theT level should be added there, the GMQL server should just take those levels and act upon them.  Please add a class for privileges and do not use easy fix by comparing the user name.

**Comment by acanakoglu** [comment]
Please update the all the services, that needs the user level, I can provide this information all the necessary services. After you finished, please let me list me all the services that needs this information. (possibly set the default to some level so, the current version will work properly with the default levels)

**Comment by andreagulino** [comment]
@marcomass Now we have these categories:
- GUEST
- BASIC
- PRO
- ADMIN
(- PUBLIC)

each assigned with a different quota and amount of spark executors

test: http://130.186.13.219/gmql-rest-test/

**Comment by marcomass** [comment]
@andreagulino @acanakoglu 
According to talks with @acanakoglu , please in the user interface show full percentage of user used space, as percentage ratio between user occupied space and user category quota, i.e. showing also % greater then 100, and provide also the occupied space in GB.

Please also consider to add an additional user category PRO2 with extended privileges than PRO (now PRO is the only not auto-registered user category).
Please also use a more proper name for the highest, currently named PUBLIC (e.g. REPO?)

I reopen this issue for these small aspects.

**Comment by acanakoglu** [comment]
As I told wrote you PUBLIC user should not be visible to the any user. So, there is no real need to change it. I am also against to create many user levels.

My answer to your email as below:

PUBLIC should not be used except public user so it doesn’t matter what the name is. So, it is not important. And also again, in a similar manner, then you should ask to change the name of the public user into the repo user( to Andrea), where we doesn’t have any advantage except then loosing time for renaming in all the code. 
I would not add many user categories as you asked, I would stay our agreement as before, only those categories that we implemented.

**Comment by marcomass** [comment]
Ok. Please provide in the interface absolute (GB) and full percentage (also >100%) of user used space
