### ISSUE TITLE
User query management 

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#12]
Make possible for any user to manage its queries, by deleting those not needed anymore, and saving on file on user laptop those to be backed-up (both for guest and registered users)

**Comment by marcomass** [comment]
There is no any confirmation request for the deletion, which can go unperceived. Could it be an issue? Can a confirmation message be added?

**Comment by acanakoglu** [comment]
The last query loaded in the query editor. if the user wrongly delete it, he can saved it again.

**Comment by marcomass** [comment]
Yes, but if he does not realize to have deleted it and load another query, the previous query is lost....
