### ISSUE TITLE
'enhancer' annotation sample 

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#15]
What's the issue in the 'enhancer' annotation sample which prevents its materialization when selected?

Running:
DATA_SET_VAR = SELECT(annotation_type == 'enhancer') HG19_BED_ANNOTATION;
MATERIALIZE DATA_SET_VAR INTO RESULT_DS;
the generated datest is empty (both in GTF and tab format)

**Comment by acanakoglu** [comment]
The related file have one column(strand) less then defined in the schema. It is added to the file.
