### ISSUE TITLE
Schema name for private datasets

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#16]
Correctly report the Schema name for private datasets as for public ones (for private ones now it is reported "DatasetName_SCHEMAS")

**Comment by akaitoua** [comment]
fixed.

**Comment by marcomass** [comment]
@acanakoglu This is now correct, but the dataset name reported in the schema section of the page is very long and alters the layout of the entire page; can it be wrapped?

**Comment by acanakoglu** [comment]
The dataset name information from schema has been removed from the user interface.
