### ISSUE TITLE
Killed job message

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#19]
When a job is killed, show “EXEC_STOPPED” instead of “EXEC_FAILED”

**Comment by andreagulino** [comment]
I made the required [changes](https://github.com/DEIB-GECO/GMQL/commit/ab8d9ab360ba0944ff1ce5a661ffcfee5bf6e5d8) on the GMQL repository, I see that nothing needs to be changed in GMQL-WEB.
