### ISSUE TITLE
Dataset quantitative features

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#2]
Provide information about the size (in byte), number of samples and the number of regions in a dataset (and the number of regions in a sample), besides the date of each dataset

**Comment by akaitoua** [comment]
@acanakoglu, Mr. @andreagulino is responsible for providing this info. @andreagulino, please let me know when ever you need help. Let's close those issues as soon as we can.

**Comment by andreagulino** [comment]
@marcomass

**Comment by marcomass** [comment]
Good!
@andreagulino @acanakoglu 
In the web interface in the information window of a sample I see " Info | Sample Profile not available"
Can be shown the number of regions in a sample?

**Comment by andreagulino** [comment]
@marcomass 
This issue envolved only samples in private datasets, fixed with [this commit](https://github.com/DEIB-GECO/GMQL/commit/565f44bb07ab64391f1e94b39bcc669b66fd4346). 
P.S. The fix will apply to new generated datasets
