### ISSUE TITLE
Example query management

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#21]
Enable a structure where to incrementally store example queries (in case with their description), which can be clicked to be copied in the Query editor section to be run (for an example see http://147.8.174.16:9999/stql/queries/shared ), making easy for an administrator to add / modify example queries.

**Comment by marcomass** [comment]
Functionality is fine; some improvements as follows are useful:
- It is not intuitive that double clicking on a query name/description makes appearing the GMQL query  with the possibility to run it; can be made more clear, maybe with a different layout?
- More than 60 example queries will be loaded (now 23); initially showing them grouped by query name would be more clear, instead of having multiple pages a query names and descriptions visualized; can the layout be modified for this goal?
- When a query is copied to query editor using the defined button, please change the query name in the query editor interface to the name (short) of the copied query, for example to "Ex_select1"

**Comment by marcomass** [comment]
Query grouping should be by value of the "group" tag in json where the example queries are defined.
There, multiple queries have the same "group" value.

**Comment by acanakoglu** [comment]
Thank you for the clarification. It was not correct in the previous comment.

**Comment by marcomass** [comment]
It is important to make intuitive how to run the queries.
Shortly additional 40 queries will be added.

**Comment by marcomass** [comment]
I suggest to avoid option of reordering example queries list by column order since this results in a not useful ordering and then the original ordering cannot be restored anymore (unless window is closed and reopened).

**Comment by marcomass** [comment]
Is it possible to avoid option of reordering example queries list by column order?
(this results in a not useful ordering and then the original ordering cannot be restored anymore, unless window is closed and reopened).
