### ISSUE TITLE
Encoding 

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#24]
When uploading dataset samples some character encoding seams not working properly; in fact, when downloading metadata file some characters are not recognize in the local encoding system (e.g. ANSI - Latin1) resulting in some unreadable string (e.g. 17ï¿½ï¿½-estradiol); can the encoding info be embedded in the uploaded/downloaded file?

**Comment by marcomass** [comment]
@acanakoglu 
I set back this issue's milestone to fix bug, since it does refer to the data uploaded through the Add functionality (the one the reviewers will use ...), besides the data loaded in the repository through the GMQL inporter

**Comment by acanakoglu** [comment]
In the November version we have this issue. I cannot find in the august which will be go public. 
Please show me more examples if there are other cases with this problem.
