### ISSUE TITLE
Vertical resize of Query editor and Dataset areas

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#27]
Add possibility for the user to change the maximum number of vertical lines displaied (before the vertical scroll appears) in the Query editor and Dataset areas

**Comment by marcomass** [comment]
Very good. I see it for the query editor, but not for the Dataset area. Can you add it also for the Dataset area?

**Comment by acanakoglu** [comment]
It will not same as the other, it becomes confusing. I prefer not to do it.

**Comment by marcomass** [comment]
Done only on the query editor is useless, since it does not solve the main problem: having schema, metadata browser info far from the dataset name ...
I would apply this resize feature also to the Dataset area (which probably solve, or at least limit the main issue)

**Comment by acanakoglu** [comment]
it has been applied for the Dataset tree.
