### ISSUE TITLE
Dataset time stamp

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#28]
We need to have associated to each dataset the date of its creation.
This should be stored somewhere (possibly in the xml structure where Andrea store the dataset profiling information) at the time of the dataset creation, and then shown in the web interface (using a web service created for this aim).

**Comment by andreagulino** [comment]
@marcomass 
I think it is better to store it with the xml file listing samples, that is created with the dataset and is already accessed by the web interface. Profile.xml may be computed at different time, so it may not be able to detect when the dataset was created.

If you agree with what i said I proceed doing the required changes.

**Comment by acanakoglu** [comment]
@andreagulino , 
1) User interface is accessing the list of the samples by using the services API from repository package. The information which is saved in the file you proposed should be available by services in the same manner. 
2) You can start to create this dataset.info file when you generate the dataset. In the case of public data, there will a function to get this data from the importer package.

**Comment by andreagulino** [comment]
@marcomass see https://github.com/DEIB-GECO/GMQL-WEB/issues/51
