### ISSUE TITLE
GMQL keywords (color identified)

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#47]
Add as keywords of the language, to be shown in different color in the query editor window, the following ones:
 DIST, DG, DL BAGD
LEFT_DISTINCT, RIGHT_DISTINCT, BOTH

**Comment by marcomass** [comment]
@acanakoglu 
DL is still missing

**Comment by marcomass** [comment]
@acanakoglu 
DL and SQRT() seems still missing

**Comment by MicheleRoar** [comment]
add COUNTSAMP in recognized keyword

**Comment by marcomass** [comment]
@acanakoglu 
COUNTSAMP seems still not recognized in the query editor space

**Comment by marcomass** [comment]
STRING seems missing; please add.
