### ISSUE TITLE
Datasets info

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#51]
Extend XML schema file adding new attributes for dataset content description.

It is important to associate with each datasets some info about it and the data it contains (e.g., type of contained data, where retrieved from, creation(update date, number of samples included, amount of bytes, etc. ... 
Some of these information can be provided directly by the GMQL-Importer software, other should be provided through the solving of issue [#2](https://github.com/DEIB-GECO/GMQL-WEB/issues/2) and [#28.](https://github.com/DEIB-GECO/GMQL-WEB/issues/28)   
In the xml schema file of GMQL datasets it is important to define an" information" tag which includes several subtags, one for each info to provide (see above examples). 
This implies changing the xsd associated with the xml schema and the implementation of both the web interface (in order to make this information accessible and display it properly) and the implementation, in order to parse the xml file and make the information available to the web interface.  
It is important to make such changes to the implementation so that all subtags included in the information tag are parsed and displayed in the web interface, so that if new info are required to be displayed, it will be then enough to add them in the xml (in a proper subtag under the information tag) and change the xsd without any further change to the implementation.

**Comment by andreagulino** [comment]
@marcomass @acanakoglu @akaitoua 
I think the schema file must not be touched, both because of its semantics and because the compiler and by the implementation would need modifications to not consider the "extra" tag.

I would add this information on a new dataset metadata file, maybe stored as "dataset.meta".

**Comment by andreagulino** [comment]
@marcomass 
Dataset Metadata is now implemented in GMQL and shown in the  web interface.
At the moment we support:
- Creation Timestamp
- Size (MBs)

Missing (new milestone):
- Additional properties 
- Methods for GMQL-Importer

test: http://130.186.13.219/gmql-rest-test/

**Comment by marcomass** [comment]
Very good!
@acanakoglu @andreagulino 
Where can the Creation Timestamp and Size (MBs) of a dataset be seen in the web interface?

**Comment by andreagulino** [comment]
@marcomass on new datasets, together with the profile info

**Comment by marcomass** [comment]
@andreagulino 
Very good. Please implement also methods for GMQL-Importer, so that we can use them when will soon create new TCGA and ENCODE data, in particular to include time stamps e description for public datasets

**Comment by andreagulino** [comment]
@marcomass implemented in [this commit](https://github.com/DEIB-GECO/GMQL/commit/df9d0695af5a5436e0aa7b204dc6d28c68f177f2)

new method:
` setDatasetMeta(datasetName: String, userName: String, metaEntries:Map[String,String])`

**Comment by marcomass** [comment]
@acanakoglu @andreagulino
Please implement the use of the dataset profiler also for dataset loaded by the user through the web/rest interface, so that also for such datasets, once available in the web interface, the info are available and accessible

**Comment by andreagulino** [comment]
@marcomass Implemented

**Comment by marcomass** [comment]
@andreagulino @acanakoglu 
I updated a small dataset with custom schema but:
- On genomic I got ERROR (not more specified) with this message: "This exception has been logged with id 75p541a65"
- On Cineca I succeeded to upload the dataset, but no valuer are given by the profiler:
Average region length | undefined
Number of regions | undefined
Number of samples | undefined

I uploded this dataset:
[files.zip](https://github.com/DEIB-GECO/GMQL-WEB/files/1442084/files.zip)

I reopen this issue for this fix

**Comment by andreagulino** [comment]
@marcomass fixed

**Comment by marcomass** [comment]
Good.
Yet, time stamp and size are not included (also in the public datasets); please include them too (as before).
Can you run the profiler also for the public datasets on genomic?
