### ISSUE TITLE
Test metadata table - empty search result

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#54]
@acanakoglu 

When searching within the new metadata table after clicking on Test button, and no results are retrieved, at the table bottom it is written: "Showing 0 to 0 of 0 #{upperLeftTitle} (filtered from 40 total sample)s" 
Probably something wrong occurs with "#{upperLeftTitle}" and ")s" ...
Please fix message.

**Comment by acanakoglu** [comment]
@marcomass 
Could you please give me more details in order to replicate this result?

**Comment by marcomass** [comment]
@acanakoglu 
enter any text in the upper right search box of the test window which provides empty results, and look at the message displayed at the bottom left of the window.
