### ISSUE TITLE
Possibility to define parameters for UCSC visualization

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#57]
@acanakoglu 

Enable the Possibility to define parameters for UCSC visualization, including chromosome and genomic range of visualization, to be suggested as user modifiable default based on content of a dataset sample.   
[I think we sayed something else about this, but now I do not remember ... please add if you remember

**Comment by marcomass** [comment]
@acanakoglu 
Good. Just a small fix and a couple of questions:
- In the heather of the window for setting the parameters please change USCS to UCSC
- Why under the text boxes it is written "Help text 1." and "Help text 2."? 
- Can you please tell me how (based on which algorithm) do you define the min and max visualization range?

**Comment by acanakoglu** [comment]
> Can you please tell me how (based on which algorithm) do you define the min and max visualization range?

As a future reference, it takes the first region of first sample and it does the zoom out 3x similar to UCSC browser.
