### ISSUE TITLE
Search function in Test option of Metadata Browser

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#59]
Trying to look at the values that the metadata attribute patient_age assumes in the samples of Example_Dataset_1 (publicly available on Cineca), I select the dataset, open the Test option in the Metadata browser, transpose the visualization and type patient_age in the Search box. 
Yet, the result is empty, despite the patient_age attribute exists, with some value in some samples.
Please fix this bug.

**Comment by acanakoglu** [comment]
first column is also header so it is excluded from the search

**Comment by marcomass** [comment]
After last usage to explore metadata of results, I think it is much better to have the possibility to filter the metadata table also based on attribute names. 
As we previously discussed, can you add also first column in the search?

**Comment by acanakoglu** [comment]
As we cannot discuss this properly today and I am against it because this columns is a part of header I am closing as it is now
