### ISSUE TITLE
Dataset “vocabulary” visualization 

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#6]
Enable visualization of dataset “vocabulary”.
It requires the vocabulary file to be stored in the repository

**Comment by akaitoua** [comment]
@andreagulino, would you work with Arif to have the Vocabulary along with the samples' data statistics.

**Comment by acanakoglu** [comment]
Postponed until new repository management

**Comment by andreagulino** [comment]
@marcomass @acanakoglu 
I need more details on what you mean for "vocabulary" and what has been done so far

**Comment by acanakoglu** [comment]
@andreagulino,
You can start to check the code that creates vocabulary count stream based:
https://github.com/DEIB-GECO/GMQL-WEB/blob/master/app/utils/VocabularyCount.scala
We can meet and I can explain to you.

**Comment by acanakoglu** [comment]
The frontend functions has been added, when the backend is ready, we can connect with them.

**Comment by acanakoglu** [comment]
it is removed from the interface.
