### ISSUE TITLE
"Add" dataset window - Abort upload button + big dataset error message

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#66]
@acanakoglu 
Please add possibility to abort a dataset upload; this is very useful when a bigger dataset is being uploaded.
Currently, when a medium size dataset is uploaded, is taking some time and then a window with just a 404 error is shown, without any explanation (some explanation should be added, mentioning the max uploading size)

**Comment by acanakoglu** [comment]
user can easily refresh to stop the upload and I cannot replicate big dataset upload.

**Comment by marcomass** [comment]
Do you mean that it is enough to "refresh" (how?) to stop uploading?
How the user can know this?
If it is so, please inform someway the user about it.

**Comment by acanakoglu** [comment]
By refresh, I mean reload the page(F5 or reload/refresh button), it is standard for the tools on the internet to stop loading. 
What kind of message should we give to the user and where? 

And the uploading big dataset error is invalid.

**Comment by marcomass** [comment]
What do you mean with "error is invalid"?

**Comment by acanakoglu** [comment]
it is not replicable.
