### ISSUE TITLE
"Add" dataset window - unspecified error in uploading data

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#67]
@acanakoglu @akaitoua 
When not a small dataset is loaded, after a while of "indexing" processing an unspecified 404 error appears.
Please check why the error occurs and provide a message that clarify how to avoid the error. 

You can use the following dataset for testing (currently error occurs also selecting only 50 samples of the dataset)  
[q10new_20180302_192447_MUTATION_GENE.zip](https://github.com/DEIB-GECO/GMQL-WEB/files/1942745/q10new_20180302_192447_MUTATION_GENE.zip)

**Comment by acanakoglu** [comment]
I tried and the error cannot be replicated. As shown in the figure all 1224 files (612 samples) are uploaded correctly. I tried on the both server.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/17035988/39190066-193f9df4-47d4-11e8-991f-a68b69f52f4d.png">

**Comment by acanakoglu** [comment]
The schema doesn't have schema type, which should be GTF. 
it is not about the web interface, it is the repository manager/XSD definition problem.

**Comment by marcomass** [comment]
Ok, so, if I understand correctly, a check should be added in the repository manager/XSD definition, and a clear message about the problem in the used schema should be provided, so that the web interface can show it to the user.
@andreagulino, can you do it?

**Comment by marcomass** [comment]
very good!

**Comment by marcomass** [comment]
I further tested this user message issue and found another case of "Unknown error" when the data file content does not meet the schema structure. 
I used this testing dataset:
[testSchema_mixed.zip](https://github.com/DEIB-GECO/GMQL-WEB/files/1976485/testSchema_mixed.zip).
Please provide meaningful message to the user also in this case (e.g., "The data file content is not conform to the used schema file structure").

Furthermore, if a not xml file is used as schema file, the following error message is shown:
"The dataset schema does not confirm the schema style (XSD)
Content is not allowed in prolog."
I suggest to remove the second line "Content is not allowed in prolog." and substitute it with "Please check schema format at https://github.com/DEIB-GECO/GMQL-WEB/wiki/file_formats "

**Comment by acanakoglu** [comment]
Dear @marcomass,
The first has been resolved, if you agree please remove the test tag.
I will not do that one, we have already give the hint in that page so user, who tries to upload his own xml should understand the file will be an XML, so it is a wontfix enchancement from the link with the hint on the upload page.
