### ISSUE TITLE
“Add” dataset window improvements (multiple subissues)

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL-WEB#9]
In the “Add” window for uploading personal datasets:
- In the window title, change text “data set” to “dataset” 

- When an error occurs (e.g. a new dataset is created with the name of a data existing in the repository Private section), report why (now only “error” is reported); @akaitoua I thik this requires Abdulrahman fix 

[previous additional issues moved to issue #48 and #49]

**Comment by marcomass** [comment]
Also, revise BED format and add other BED subtypes (e.g. BED3, BED6, …)

**Comment by acanakoglu** [comment]
Postponed until new repository management

**Comment by marcomass** [comment]
@acanakoglu 
Unfortunately I need to reopen this issue since in case of not small dataset the returned error is still not explicative (“Unknow Error in the Upload”);
Please provide a clear message also in all cases of error (in particular when the error is due to size of the dataset greater than the fixed limit. 
By the way, probably the best thing is to relate this limit to the type of user and remove it for power users; don't you think?

**Comment by Kia23** [comment]
Here are some details concerning the latest post and some tests I executed:
There are no issues with my PROM dataset with 1 sample containing 49052 regions (upload process is successful); however, with my BROAD dataset obtained by filtering some data through a SELECT from HG19_ENCODE_BROAD_AUG_2017, I get the following: 
   -  No issue if I upload the first 12 samples;
   -  Error is returned if I upload the first 13, 14, 15 (and so on…) samples or the whole dataset.

I am attaching the two datasets I used for the tests.

[BROAD.zip](https://github.com/DEIB-GECO/GMQL-WEB/files/1326438/BROAD.zip)
[PROM.zip](https://github.com/DEIB-GECO/GMQL-WEB/files/1326439/PROM.zip)

**Comment by acanakoglu** [comment]
@marcomass, The request entity size has not been shown as "Unknow Error in the Upload", but it was **"413 Request Entity Too Large"**

@Kia23, the problem was resolved, please test it again.
